Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,13 +8,12 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Log in to Amazon ECR.
+      - name: Log in to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
         with:
-          region: us-east-1
+          region: ${{ secrets.AWS_REGION }}        
           mask-password: true
           registry-type: private
           skip-logout: false
@@ -26,18 +25,18 @@ jobs:
         uses: docker/setup-buildx-action@v1
 
       - name: Build and Push Docker Image
+        env:
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}        
+          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
         run: |
-          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }} .
-          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }}
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+          set -e  # Exit on non-zero exit code from commands below
+          docker buildx build --platform linux/amd64,linux/arm64 \
+            -t ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$${{ env.AWS_ACCOUNT_ID }}/{{ env.IMAGE_NAME }}:${{ github.sha }} .
+          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$${{ env.AWS_ACCOUNT_ID }}/{{ env.IMAGE_NAME }}:${{ github.sha }}
 
       - name: Deploy to EKS
         run: |
+          set -e  # Exit on non-zero exit code from commands below
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml
